### ISSUE TITLE
Simple auth UI for discord join flow

### ISSUE THREAD

**Issue by Brunya** [AgoraSpaceDAO/guild.xyz#79]

**Comment by Brunya** [comment]
<img width="1286" alt="Screenshot 2021-11-08 at 19 39 35" src="https://user-images.githubusercontent.com/32143596/140798923-d980373a-95d9-4e85-9497-c64de7d4c911.png">
Something like this (without hovered background)
This is a separated page. /auth/:discordId maybe but you should ask Devid

**Comment by dovalid** [comment]
done in #28
